from enum import Enum

class EventPriority(int, Enum):
    CRITICAL = 0
    HIGH = 1
    NORMAL = 5
    LOW = 10

class EventSource(str, Enum):
    TERMINAL = "terminal"
    VOICE = "voice"
    MEMORY = "memory"
    AUDIO = "audio"
    SYSTEM = "system"
    FUTURE_SENSOR = "future_sensor"
    FUTURE_ROBOT = "future_robot"

class EventType(str, Enum):
    TERMINAL_INPUT_RECEIVED = "TERMINAL_INPUT_RECEIVED"
    VOICE_AUDIO_RECORDED = "VOICE_AUDIO_RECORDED"
    VOICE_TRANSCRIPT_READY = "VOICE_TRANSCRIPT_READY"
    USER_MESSAGE_READY = "USER_MESSAGE_READY"
    ASSISTANT_RESPONSE_READY = "ASSISTANT_RESPONSE_READY"
    MEMORY_EXTRACTION_REQUESTED = "MEMORY_EXTRACTION_REQUESTED"
    MEMORY_EXTRACTION_COMPLETED = "MEMORY_EXTRACTION_COMPLETED"
    MEMORY_CONSOLIDATION_REQUESTED = "MEMORY_CONSOLIDATION_REQUESTED"
    MEMORY_REFLECTION_REQUESTED = "MEMORY_REFLECTION_REQUESTED"
    MEMORY_DECAY_REQUESTED = "MEMORY_DECAY_REQUESTED"
    MEMORY_ARCHIVAL_REQUESTED = "MEMORY_ARCHIVAL_REQUESTED"
    TTS_SYNTHESIS_REQUESTED = "TTS_SYNTHESIS_REQUESTED"
    TTS_SYNTHESIS_COMPLETED = "TTS_SYNTHESIS_COMPLETED"
    AUDIO_PLAYBACK_REQUESTED = "AUDIO_PLAYBACK_REQUESTED"
    AUDIO_PLAYBACK_COMPLETED = "AUDIO_PLAYBACK_COMPLETED"
    SYSTEM_HEALTH_CHECK_REQUESTED = "SYSTEM_HEALTH_CHECK_REQUESTED"
    FUTURE_SENSOR_EVENT_RECEIVED = "FUTURE_SENSOR_EVENT_RECEIVED"
    FUTURE_ROBOT_EVENT_RECEIVED = "FUTURE_ROBOT_EVENT_RECEIVED"
