from enum import Enum

class TaskType(str, Enum):
    MEMORY_EXTRACTION = "MEMORY_EXTRACTION"
    MEMORY_EMBEDDING = "MEMORY_EMBEDDING"
    MEMORY_CONSOLIDATION = "MEMORY_CONSOLIDATION"
    MEMORY_REFLECTION = "MEMORY_REFLECTION"
    MEMORY_DECAY = "MEMORY_DECAY"
    MEMORY_ARCHIVAL = "MEMORY_ARCHIVAL"
    TTS_SYNTHESIS = "TTS_SYNTHESIS"
    AUDIO_PLAYBACK = "AUDIO_PLAYBACK"
    AUDIO_CLEANUP = "AUDIO_CLEANUP"
    CACHE_REFRESH = "CACHE_REFRESH"

class TaskPriority(int, Enum):
    LOW = 10
    NORMAL = 5
    HIGH = 1
    CRITICAL = 0
