from enum import Enum

class LLMRole(str, Enum):
    CONVERSATION = "CONVERSATION"
    CLASSIFIER = "CLASSIFIER"
    MEMORY_EXTRACTOR = "MEMORY_EXTRACTOR"
    SUMMARIZER = "SUMMARIZER"
    EMBEDDER = "EMBEDDER"
